export const authConstants={
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstant={
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE'
}
export const catergorConstant={
    GET_ALL_CATERGORY_REQUEST: 'GET_ALL_CATERGORY_REQUEST',
    GET_ALL_CATERGORY_SUCCESS: 'GET_ALL_CATERGORY_SUCCESS',
    GET_ALL_CATERGORY_FAILURE: 'GET_ALL_CATERGORY_FAILURE',
    ADD_NEW_CATERGORY_REQUEST: 'ADD_NEW_CATERGORY_REQUEST',
    ADD_NEW_CATERGORY_SUCCESS: 'ADD_NEW_CATERGORY_SUCCESS',
    ADD_NEW_CATERGORY_FAILURE: 'ADD_NEW_CATERGORY_FAILURE'
}
export const productConstant={
    GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAILURE: 'GET_ALL_PRODUCT_FAILURE'
}
export const medicineConstant={
    GET_ALL_MEDICINE_REQUEST: 'GET_ALL_MEDICINE_REQUEST',
    GET_ALL_MEDICINE_SUCCESS: 'GET_ALL_MEDICINE_SUCCESS',
    GET_ALL_MEDICINE_FAILURE: 'GET_ALL_MEDICINE_FAILURE'
}

export const initialDataConstant={
    GET_ALL_INITIALDATA_REQUEST: "GET_ALL_INITIALDATA_REQUEST",
    GET_ALL_INITIALDATA_SUCCESS: "GET_ALL_INITIALDATA_SUCCESS",
    GET_ALL_INITIALDATA_FAILURE: "GET_ALL_INITIALDATA_FAILURE"
}
export const getDoctorConstant={
    GET_ALL_GETDOCTOR_REQUEST:"GET_ALL_GETDOCTOR_REQUEST",
    GET_ALL_GETDOCTOR_SUCCESS:"GET_ALL_GETDOCTOR_SUCCESS",
    GET_ALL_GETDOCTOR_FAILURE:"GET_ALL_GETDOCTOR_FAILURE"
}
export const getPatientConstant={
    GET_ALL_PATIENT_REQUEST:"GET_ALL_PATIENT_REQUEST",
    GET_ALL_PATIENT_SUCCESS:"GET_ALL_PATIENT_SUCCESS",
    GET_ALL_PATIENT_FAILURE:"GET_ALL_PATIENT_FAILURE"
}